### ISSUE TITLE
Screenshots (v 10.1.0) stops working if you start the Nightly try build with a profile created on older Nightly builds

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3027]
[Notes]:
- This issue is not reproducible if you start the Nightly try build with a profile created on the latest Nightly (Build ID: 20170613030203) build.
- I am concerned about the fact that this issue might be reproduce on the latest Nightly build when Screenshots v. 10.1.0 will be uplifted.

[Affected versions]:
- Nightly 56.0a1
- Screenshots 10.1.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]
- Have a older profile created on a older Nightly build (eg: Nightly build from 2017-06-11).

[Steps to reproduce]:
1. Start the Nightly try build with the profile from prerequisites (Here is the Nightly try build: https://goo.gl/CwV37x).
2. Click the Screenshots icon from browser toolbar.
3. Observe the browser behavior.

[Expected result]:
- The Screenshots overlay covers the entire page and the Onboarding tour is displayed.

[Actual results]:
- The button is clickable but nothing happens.

[Additional Notes]:
- There is no treeherder build to test on Linux.
- Here is a screenshots with browser console errors:
![screenshots stops working](https://user-images.githubusercontent.com/19226534/27085494-1647f958-5058-11e7-9e71-11d2b0d972c6.png)
- Here is a screen recording with the issue:
![screenshots stops working](https://user-images.githubusercontent.com/19226534/27085512-24dde248-5058-11e7-8c6b-107489c14dd1.gif)

**Comment by ianb** [comment]
I haven't been able to reproduce this. I'm using [this dmg](https://archive.mozilla.org/pub/firefox/try-builds/ibicking@mozilla.com-7ec9a69734491865e7f1490b39b8f28b0678ed9a/try-macosx64/firefox-56.0a1.en-US.mac.dmg).  I tried a few things, with a freshly-created profile each time:

1. Start newest Firefox Beta, enable Screenshots, take a shot
2. Start Firefox Nightly with 10.1.0, open about:support, click button
3. My Shots starts as normal

Or:

1. Start newest Firefox Beta, enable Screenshots, do not take a shot
2. Start Firefox Nightly with 10.1.0, open about:support, click button
3. Goes to `#hello` and starts onboarding as expected

Or:

1. Start newest Firefox Nightly (that does not have 10.1.0), do not start Screenshots
2. Start Firefox Nightly with 10.1.0, open about:support, click button
3. Goes to `#hello`, etc

Or:

`Error: Missing host permission for the tab`

1. Start newest Firefox Nightly, take a shot
2. Start Firefox Nightly with 10.1.0, take a shot
3. Works as expected

BUT!

Generally if we start Firefox with 10.1.0, go to about:home, and hit the Screenshots button, all within the first 5 seconds of startup, then it doesn't go to My Shots, and it doesn't give any error.  After 5 seconds it will give an error.

**Comment by 6a68** [comment]
Sounds like a non-blocker to me, but SV should continue to investigate as newer Nightlies land

**Comment by 6a68** [comment]
I tried to repro on mac and windows, and wasn't able to repro on either. @SoftVision-CosminMuntean are you still able to repro from a fresh profile on an older Nightly?

**Comment by SoftVision-CosminMuntean** [comment]
I can also reproduce this issue on my computer from home on Windows 10 x64.
@6a68 can you please try the following steps on Windows?

1. Download Firefox Beta from here: https://archive.mozilla.org/pub/firefox/candidates/55.0b1-candidates/build4/win64/en-US/
2. Start the Firefox Beta browser with a new clean profile.
3. From "about:config: page enable Screenshots and close the browser.
4 Start the Nightly try build with the profile created in step 2 (here is the Nightly try build: https://goo.gl/CwV37x).
5. Click the Screenshots button from browser toolbar.

[Actual results]:
- The button is clickable but nothing happens.

I have also observed that the "Take a Screenshot" option from context menu is no longer displayed.
Here is a more detailed screen recording with the issue: https://goo.gl/aBB6P3

**Comment by 6a68** [comment]
I'm able to repro this error on Windows. Thanks for the STR, @SoftVision-CosminMuntean :+1:

I can reproduce this bug regardless of whether I complete onboarding in Beta before reopening the same profile in the Nightly Try build.

Investigating.

**Comment by ianb** [comment]
In case it's something weird with the build, I kicked off [another Try run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=b64b547c6b9e26ab0a2d1c6f3c8f913818d854b3)

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Turns out the linux build is hidden inside the 'tc' task:

![](https://screenshots.firefoxusercontent.com/images/0954a370-51ad-4529-8dbb-00e0622889b7.png)

**Comment by 6a68** [comment]
Apparently Beta build 4 is not considered a working build, so we should focus on STR that involve old Nightly / new Nightly

**Comment by ianb** [comment]
[A second build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=8e50ad286259711a0c0a05d10ff392f3c52acf98) with the latest changes from central merged.

**Comment by 6a68** [comment]
I'm able to reproduce on Mac by creating a new profile in [the 2017-06-11-03-02-08 nightly](https://download-origin.cdn.mozilla.net/pub/firefox/nightly/2017/06/2017-06-11-03-02-08-mozilla-central/), then opening the same profile in Ian's try build from yesterday.

No useful errors seem to be logged to the console. When I launch the Try build from the terminal, I see some error messages, but they all seem to be the known harmless bootstrap_register errors mentioned in [this dev-platform thread](https://groups.google.com/forum/#!topic/mozilla.dev.platform/O7y368bgGFQ) and tracked by [bug 1306663](https://bugzilla.mozilla.org/show_bug.cgi?id=1306663).

I'm currently walking through the addon initialization steps by force-reloading the addon from the Browser Toolbox. This can be done as follows:

```js
// inside the browser toolbox console
AddonManager.getAddonByID('screenshots@mozilla.org')
  .then(addon => window.screenshotsAddon = addon)
// take a moment to set some breakpoints, then reload:
screenshotsAddon.reload()
```

You can set breakpoints inside the browser toolbox like this:

for bootstrap.js, look inside `jar://`:
<img width="444" alt="screen shot 2017-06-13 at 12 51 27 pm" src="https://user-images.githubusercontent.com/96396/27101611-51077544-5037-11e7-8c57-7e951874f28b.png">

for the webextension, it's easier - the code's inside `moz-extension://`:
<img width="196" alt="screen shot 2017-06-13 at 12 54 05 pm" src="https://user-images.githubusercontent.com/96396/27101687-9eda2c76-5037-11e7-94bc-b773ad3a349a.png">

**Comment by 6a68** [comment]
Aha! `startBackground.js` is missing from the webextension, which I think explains why the Try build is busted.

@ianb I think it's necessary to re-export each time you switch branches, rather than cherry-pick changes from one git-cinnabar branch to another. I'm guessing one of the exports just grabbed a few little changes, but missed a big chunk of stuff.

This is not a blocker and not a real bug. Closing.

**Comment by 6a68** [comment]
Reopening: `startBackground.js` [is present](https://hg.mozilla.org/try/diff/64f6f06568df/browser/extensions/screenshots/webextension/background/startBackground.js) in the Try build, and it's addressable via a `resource://` URL, it just doesn't seem to have gotten loaded. This may have been a Nightly bug from that particular day, but this isn't yet resolved.

**Comment by ianb** [comment]
We've identified that this is not a packaging bug.

I was originally trying to reproduce with the 6-13 Nightly, while Cosmin and Jared used the 6-11 version.  I changed to the 6-11 version and was also able to reproduce the problem.

**Comment by 6a68** [comment]
TIL that `about:buildsettings` in Nightly tells you the mercurial commit from which the build was created. The commit SHAs can then be passed into a URL of the form `https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=XXX&tochange=YYY` to look at a set of results.

Between the first 6/11 build, and the latest 6/13 build, there is a pretty large set of patches: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=799d43edb324395cf02da6b028e803712334615f&tochange=5293e5f8935831e2e0d91ac9b69c1b473b3c0177

**Comment by ianb** [comment]
Here's my best understanding of what's happening:

- When you start the new build, you get all the new files
- But you get the *old* manifest.  The version is 9.0.0, and background.scripts is the old value
  - You can inspect the manifest with the debugger, executing `browser.runtime.getManifest()`
  - If you get the UUID, you can confirm the content of the actual files, and see that `main.js` has `exports.onClicked=...` (the 10.1.0 version) instead of `browser.browserAction.onClicked=...` (the 9.0.0 version)
- This happens going from Firefox 55 Nightly to the Firefox 56 Nightly with Screenshots 10.1.0; if you use Firefox 56 (6-13's Nightly) and then use the Firefox 56 Nightly with 10.1.0, the upgrade happens correctly

**Comment by 6a68** [comment]
Apparently a startup reason has to be passed to the Extension for the startup cache to be invalidated. This isn't supported currently, so I've filed a bug to add it: https://bugzilla.mozilla.org/show_bug.cgi?id=1372750

I suppose the only thing we can do, in this situation, is to move the contents of startBackground.js back into one of the files that exists in the older manifest ([here](https://github.com/mozilla-services/screenshots/commit/8f9857958de7ca9a14eb888850996ca7c02b3029) is a relevant diff). 

If we aren't able to resolve this issue, I'm not sure we should ship in 55. Adding the blocker tag accordingly.

**Comment by 6a68** [comment]
Hmm. If we can't update the manifest, that means we can't actually defer loading the scripts (which was the whole point of adding `startBackground.js` in the first place). This means Screenshots may have a greater-than-expected impact on startup performance.

Oddly, since Talos works with a fresh profile every time, this regression might not be caught by Talos.

**Comment by 6a68** [comment]
aswan pointed out that we can just call the cache invalidation code ourselves, inside bootstrap.js. Working on a patch now.

**Comment by 6a68** [comment]
Here is a summary of the current state of this bug, pulled from IRC:

When we made our background page lazy load all the scripts, we did that by pulling lots of scripts out of the webextension manifest, instead just loading one script that waits to load the rest. You can see that [here](https://github.com/mozilla-services/screenshots/commit/8f9857958de7ca9a14eb888850996ca7c02b3029#diff-edd690115570044e76445f43adc8ba8b).

It turns out that change isn't recognized in some cases, because the old manifest.json is permanently cached. So startBackground.js, the new file, is never loaded, which causes the extension to break. What's worse, in such a situation, all the old files will be loaded at startup time, causing performance regression (that Talos couldn't discover, since it uses a fresh profile each time) The good news is that we can manually force the cache to be cleared.

I've opened a pull request with the manual StartupCache clearing, and I've also exported the StartupCache clearing code to Firefox and pushed to Try.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean I've pushed a possible fix to Try. Please test and let us know if the bug can still be reproduced:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=68a74ca205964c17b3406dade1b5647949848c28

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest provided try build and is no longer reproducible for profiles created on latest Beta candidate, or older Nightly builds with Screenshots v8.0.0 or v9.0.0.
I have tested this on Mac Os and also on Windows.

But, it seems that Screenshots is still not working and the icon is no longer displayed in browser toolbar, if you start the Nightly try build with a profile created on older Nightly builds with Screenshots v.6.6.0. 

[Steps to reproduce]:
1. Download Nightly build from 2017-05-12 from here: https://archive.mozilla.org/pub/firefox/nightly/2017/05/2017-05-12-03-02-03-mozilla-central/
2. Start the Nightly build with a new clean profile.
3. Navigate to "about:config: page, enable Screenshots and close the browser.
4. Start the Nightly try build with the profile created in step 2 (here is the [Nightly try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=68a74ca205964c17b3406dade1b5647949848c28))
5. Observe the browser toolbar.

[Actual results]:
- The Screenshots icon is no longer displayed.

[Notes]:
- Even if you restart the browser or re-enable Screenshots from "about:config" the Screenshots icon is not displayed.
- Here is a screen recording with the issue: https://goo.gl/5LN4nG
- Here is a screenshot with  browser console error:
![screenshots 6](https://user-images.githubusercontent.com/19226534/27131829-1566c010-5115-11e7-8d07-83e7e4733c9d.png)

Let me know if I should log another issue for this.

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the above described issue is not reproducible on Nightly build from 2017-05-29 where Screenshots 6.6.0 is enabled by default. Probably this issue is only reproducible on Nightly builds with Screenshots 6.6.0 disabled by default.

Considering this, from my point of view this issue is no longer a blocker for Beta.
