### ISSUE TITLE
Enable Firefox Accounts on stage/prod

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4308]
This one's for @oremj. We've got FxA working on dev. Is there any additional setup work required to get it working on stage / prod? The Screenshots server will need to make outgoing connections to some FxA endpoints, which might require firewall changes.

**Comment by wresuolc** [comment]
Let's get it going on stage and verify it before turning on in prod. 

/cc @jvehent just fyi

**Comment by wresuolc** [comment]
@oremj do you need anything from us to enable this on stage?

**Comment by oremj** [comment]
@jbuck can you generate FXA ids and secrets for this?

Domains are:

stage: screenshots.stage.mozaws.net
production: screenshots.firefox.com

**Comment by jbuck** [comment]
@oremj - I added the fxa client id and secret to hiera-sops in commit 65e2dbdb0ee589c26ca46c4a6a4857f6393c04ae

**Comment by oremj** [comment]
The credentials have been pushed to stage and are queued for production when ready.

**Comment by wresuolc** [comment]
@autrilla might be able to help too

**Comment by ianb** [comment]
These are the settings that are probably already done, that enable FxA access:

* FXA_OAUTH_URI (has a default)
* FXA_PROFILE_URI (has a default)
* FXA_CLIENT_ID
* FXA_CLIENT_SECRET

But this one is probably missing, which enables the link to the FxA interface:

* `USER_SETTINGS=true`

**Comment by wresuolc** [comment]
@oremj I think the only thing missing is USER_SETTINGS=true ^^

**Comment by 6a68** [comment]
@autrilla @oremj Bumping this issue

**Comment by autrilla** [comment]
Do you just need the env var `USER_SETTINGS` set to `true` in stage?

**Comment by chenba** [comment]
@autrilla Yes, please.

**Comment by autrilla** [comment]
The env var is set in stage now.

**Comment by chenba** [comment]
Thanks!

I don't know what version was on stage when this issue was created, but the version on stage now is running some older code, where a couple of the env var names do not match what's currently in master.  The reason for the old code was the backport we did when we were informed that some shots were indexed by search engines.

**Comment by chenba** [comment]
Now that I have access to the `cloudops-deployement` repo, I think I can ask for the right things. 😀 

Per env.

#### dev 
- `FXA_OAUTH_SERVER` should be renamed to `FXA_OAUTH_URI`
- `PROFILE_SERVER` should be renamed to `FXA_PROFILE_URI`

dev is working right now because of default values.  So these changes are not totally necessary.  But we should.

#### stage
- It needs an appropriate `FXA_OAUTH_URI`
- It needs an appropriate `FXA_PROFILE_URI`

#### prod

We talked about this in our daily meeting today, and we want FxA off in prod for now.

- Set `USER_SETTINGS` to false.  The default is true so we need to add this to prod.

**Comment by chenba** [comment]
@oremj do you need more info from us or have any questions regarding my previous comment?

**Comment by oremj** [comment]
Changed settings in: https://github.com/mozilla-services/cloudops-deployment/pull/2347

**Comment by wresuolc** [comment]
Closing this tracker bug

**Comment by chenba** [comment]
Stage doesn't have the correct client id?  I'm getting the "Unknown client" error instead of a login page.

**Comment by clouserw** [comment]
@oremj would you verify the IDs?

**Comment by oremj** [comment]
Verifying with @jbuck now.

**Comment by oremj** [comment]
I configured the URIs to point to FXA stage, but the credentials are for FXA production. 

@clouserw Do you want stage pointing at FXA stage or prod?

**Comment by clouserw** [comment]
FxA prod

**Comment by oremj** [comment]
Done in https://github.com/mozilla-services/cloudops-deployment/pull/2371. Deploying now.

**Comment by chenba** [comment]
Upon successful auth I got a server error from Screenshots.  I think it was a state mis-match.  Let's keep this open to investigate.  FxA working on dev lead me to believe that it could be config issue still.

**Comment by chenba** [comment]
Now I see a 500 on the GET to https://screenshots.stage.mozaws.net/api/fxa-oauth/confirm-login after successful FxA auth.  A bad state should cause a 403, not 500.  @oremj let me know what you need in order to figure this out.

**Comment by chenba** [comment]
I think the FXA_PROFILE_URI is incorrect.  I will file a pull request in cloudops-deployment to fix it.

**Comment by chenba** [comment]
Created https://github.com/mozilla-services/cloudops-deployment/pull/2447 to update the profile uri.

**Comment by oremj** [comment]
This change has been deployed.

**Comment by chenba** [comment]
w00t.  It works.  Closing this issue.  We'll file a new one when it's time to enable FxA on prod.
